# Generated by Django 2.1.2 on 2018-11-30 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estrategia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estrategia_id', models.IntegerField(default=0)),
                ('Hay_estrategia_asignaturas', models.BooleanField(default=False)),
                ('Hay_estrategia_posgrado', models.BooleanField(default=False)),
                ('Descripcion', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
