# Generated by Django 2.1.2 on 2018-11-30 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Estrategias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estrategia',
            name='Estrategia_id',
        ),
    ]
