# Generated by Django 2.1.2 on 2018-11-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estrategias', '0002_remove_estrategia_estrategia_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='estrategia',
            name='Estrategia_id',
            field=models.IntegerField(default=0),
        ),
    ]
