# Generated by Django 2.1.2 on 2018-11-30 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estrategias', '0004_auto_20181130_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estrategia',
            name='Hay_estrategia_asignaturas',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='estrategia',
            name='Hay_estrategia_posgrado',
            field=models.BooleanField(default=False),
        ),
    ]
