# Generated by Django 2.1.3 on 2018-12-04 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=200)),
                ('responsabilidad', models.CharField(choices=[('Institucional', 'Institucional'), ('Unidad academica', 'Unidad academica'), ('Programa', 'Programa'), ('Externo', 'Externo')], default='', max_length=20)),
                ('ultimo_anio', models.IntegerField(default=None)),
                ('penultimo_anio', models.IntegerField(default=None)),
                ('antepenultimo_anio', models.IntegerField(default=None)),
                ('numero_participantes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Desarrollo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estrategia_id', models.IntegerField(default=0)),
                ('Hay_estrategia_asignaturas', models.BooleanField(default=False)),
                ('Hay_estrategia_posgrado', models.BooleanField(default=False)),
                ('Descripcion', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=200)),
                ('beneficios', models.TextField(blank=True, default='')),
            ],
        ),
    ]
