# Generated by Django 2.1.3 on 2018-12-04 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0002_delete_desarrollo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cursos',
            new_name='Curso',
        ),
    ]
