# Generated by Django 2.1.3 on 2018-12-04 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0003_auto_20181204_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desarrollo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hay_plan_permanente_superacion', models.BooleanField(default=False)),
                ('hay_programas_superacion', models.BooleanField(default=False)),
                ('hay_otra_modalidad', models.BooleanField(default=False)),
                ('descripcion_modalidad', models.TextField(blank=True, default='', null=True)),
                ('hay_plan_formacion', models.BooleanField(default=False)),
                ('nivel_responsabilidad', models.CharField(choices=[('Institucional', 'Institucional'), ('Unidad academica', 'Unidad academica'), ('Programa', 'Programa')], default='', max_length=20)),
                ('descripcion_formacion', models.TextField(blank=True, default='', null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cursos.Curso')),
            ],
        ),
    ]
