# Generated by Django 2.1.3 on 2018-12-04 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0004_desarrollo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desarrollo',
            name='question',
        ),
        migrations.AddField(
            model_name='desarrollo',
            name='cursos',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Cursos.Curso'),
        ),
        migrations.AddField(
            model_name='desarrollo',
            name='programas',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Cursos.Programa'),
        ),
    ]
