# Generated by Django 2.1.3 on 2018-12-04 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0005_auto_20181204_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desarrollo',
            name='cursos',
        ),
        migrations.RemoveField(
            model_name='desarrollo',
            name='programas',
        ),
    ]
