# Generated by Django 2.1.3 on 2018-12-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0006_auto_20181204_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='curso',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='desarrollo',
            name='desarrollo_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='programa',
            name='programa_id',
            field=models.IntegerField(default=0),
        ),
    ]
