# Generated by Django 2.1.3 on 2018-12-06 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0007_auto_20181205_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desarrollo',
            name='nivel_responsabilidad',
            field=models.CharField(choices=[('Institucional', 'Institucional'), ('Unidad academica', 'Unidad academica'), ('Programa', 'Programa')], default='Elegir', max_length=20),
        ),
    ]
