# Generated by Django 2.1.3 on 2018-12-12 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0008_auto_20181206_2151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='curso',
            new_name='curso_id',
        ),
    ]
