# Generated by Django 2.1.3 on 2018-12-12 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0012_auto_20181212_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='antepenultimo_anio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='numero_participantes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='penultimo_anio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='ultimo_anio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
