# Generated by Django 2.1.3 on 2018-12-06 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Procesos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contratacion',
            new_name='Proceso',
        ),
    ]
