# Generated by Django 2.1.3 on 2018-12-06 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Procesos', '0002_auto_20181206_2153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proceso',
            old_name='Descripcion',
            new_name='Descripcion_Proceso',
        ),
        migrations.RenameField(
            model_name='proceso',
            old_name='Hay_estrategia_asignaturas',
            new_name='Existe_proceso_formal',
        ),
        migrations.RenameField(
            model_name='proceso',
            old_name='Hay_estrategia_posgrado',
            new_name='Hay_reglamento',
        ),
        migrations.RemoveField(
            model_name='proceso',
            name='Estrategia_id',
        ),
        migrations.AddField(
            model_name='proceso',
            name='Proceso',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='proceso',
            name='evidencia',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
