# Generated by Django 2.1.3 on 2018-12-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Procesos', '0005_auto_20181206_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceso',
            name='evidencia',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
