# Generated by Django 2.1.3 on 2018-12-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Procesos', '0006_auto_20181212_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceso',
            name='evidencia',
            field=models.FileField(blank=True, null=True, upload_to='evidencias/'),
        ),
    ]
